# Generated by Django 5.0 on 2023-12-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['auth_name'], 'verbose_name': 'Author Details', 'verbose_name_plural': 'All Registered Author Detail'},
        ),
        migrations.AlterModelTableComment(
            name='book',
            table_comment='Book Entry',
        ),
    ]
