# Generated by Django 5.0 on 2023-12-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_management', '0002_alter_author_options_alter_book_table_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Single Book Details', 'verbose_name_plural': 'All Registered Book Detail'},
        ),
        migrations.AlterModelTableComment(
            name='book',
            table_comment=None,
        ),
    ]
