# Generated by Django 5.0 on 2023-12-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('semail', models.EmailField(max_length=254)),
                ('scourse', models.ManyToManyField(to='stc.course')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('temail', models.EmailField(max_length=254)),
                ('tcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stc.course')),
            ],
        ),
    ]
